module.exports = (path) => ({
    Dropzone: {
        props: {
            label: 'Upload File',
            accept: `
                image/jpeg,
                image/png,
                image/psd,
                image/tiff,
                image/gif,
                .aac,
                audio/ogg,
                audio/x-ms-wma,
                .flac,
                .alac,
                .alac,
                .wav,
                .mp3,
                .cpm,
                .aiff,
                .webm,
                .mpg,
                .mp2,
                .mpeg,
                .mpe,
                .mpv,
                .ogg,
                .mp4,
                .m4p,
                .m4v,
                .avi,
                .wmv,
                .mov,
                .qt,
                .flv,
                .swf,
                .avchd,
                .obj,
                .fbx,
                .potx,
                application/pdf,
                application/msword,
                application/vnd.openxmlformats-officedocument.wordprocessingml.document,
                application/vnd.ms-powerpoint,
                application/vnd.openxmlformats-officedocument.presentationml.presentation,
                application/vnd.ms-excel,
                application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,
                .odf,
                .csv,
                application/x-iwork-pages-sffpages,
                application/x-iwork-keynote-sffkey,
                application/x-iwork-numbers-sffnumbers,
                application/acad,
            `,
            multiple: false,
            upload: {
                action: 'API',
                request: {
                    url: '`$data.app.settings.FileAPI.value`/upload',
                    method: 'POST',
                    withCredentials: true,
                    data: {
                        file: '$data.files.0',
                        tagToField: 'toolkitArticleId',
                        tagToId: `$data.${ path }._id`,
                    },
                },
                thumbnail: '$data.image',
            },
            onSuccess: [{
                action: 'rerender',
                arguments: {
                    name: 'mediafiles',
                },
            },
            {
                action: 'close',
                arguments: {
                    element: 'SideSheet',
                },
            },
            ],
        },
    },
});
