module.exports = {
    _id: '$data._id',
    link: '$data.link',
    name: '$data.name',
    articleName: '$data.articleName',
    publicationDate: '$data.publicationDate',
    articlePdfId: '$data.articlePdfId',
    isCoverStory: '$data.isCoverStory',
    interviewedPersonId: '$data.interviewedPersonId',
    coverageSummary: '$data.coverageSummary',
    locationCovered: '$data.locationCovered',
    articlePdf: {
        from: 'HUB',
        request: {
            model: 'files',
            type: 'query',
            query: 'File',
            arguments: {
                _id: '$data.document.articlePdfId',
            },
            resolve: {
                creator: true,
                _id: true,
                bucket: true,
                customFields: true,
                extension: true,
                meta: true,
                name: true,
                size: true,
                title: true,
                type: true,
                url: true,
                settings: true,
                previewForFileId: true,
                previewIds: true,
                updatedAt: true,
                createdAt: true,
            },
        },
        value: '$data',
    },
    interviewedPerson: {
        from: 'HUB',
        request: {
            model: 'com.hub365.people.models.People',
            type: 'query',
            query: 'SearchPeople',
            arguments: {
                raw_query: {
                    terms: {
                        _id: '$data.document.interviewedPersonId',
                    },
                },
            },
            resolve: {
                _id: true,
                name: true,
                office: true,
                title: true,
                avatarId: true,
                primaryEmail: true,
                internalMappingId: true,
                internalMappingIds: true,
                phones: true,
                status: true,
                user: true,
            },
        },
        value: '$data.values',
    },
};
